"""Add Settings and APIKey tables

Revision ID: 27508406486d
Revises: 4ac6e26860a5
Create Date: 2026-06-12 10:15:21.221151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '27508406486d'
down_revision: Union[str, Sequence[str], None] = '4ac6e26860a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_exhausted', sa.Boolean(), nullable=False),
    sa.Column('exhausted_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_api_key_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_api_key_id'], ['apikey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
