"""add sample_audio_url to character

Revision ID: 4ac6e26860a5
Revises: 1d70e0c3b7ff
Create Date: 2026-06-10 21:34:22.658408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ac6e26860a5'
down_revision: Union[str, Sequence[str], None] = '1d70e0c3b7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('sample_audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_column('character', 'sample_audio_url')
    # ### end Alembic commands ###
