"""Add alias to ProjectCharacterLink

Revision ID: 4e05a0f7a7eb
Revises: 27508406486d
Create Date: 2026-06-12 18:33:25.359135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e05a0f7a7eb'
down_revision: Union[str, Sequence[str], None] = '27508406486d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectcharacterlink', sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('sceneline', 'is_manual_phonetics',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sceneline', 'is_manual_phonetics',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('projectcharacterlink', 'alias')
    # ### end Alembic commands ###
