"""Add gender and age_category to Character

Revision ID: 73663a0b4429
Revises: 98ed14fde0f4
Create Date: 2026-06-05 15:17:52.785581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73663a0b4429'
down_revision: Union[str, Sequence[str], None] = '98ed14fde0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('character', sa.Column('age_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'age_category')
    op.drop_column('character', 'gender')
    # ### end Alembic commands ###
