"""Add raw_text to Scene

Revision ID: 982e1e553b06
Revises: 73663a0b4429
Create Date: 2026-06-06 21:59:41.110651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '982e1e553b06'
down_revision: Union[str, Sequence[str], None] = '73663a0b4429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene', sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene', 'raw_text')
    # ### end Alembic commands ###
