"""add_scenes_and_scenelines

Revision ID: 98ed14fde0f4
Revises: bdd37eac4097
Create Date: 2026-06-04 20:18:08.018355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98ed14fde0f4'
down_revision: Union[str, Sequence[str], None] = 'bdd37eac4097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_project_id'), 'scene', ['project_id'], unique=False)
    op.create_table('sceneline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language_override', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_override', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sceneline_character_id'), 'sceneline', ['character_id'], unique=False)
    op.create_index(op.f('ix_sceneline_scene_id'), 'sceneline', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sceneline_scene_id'), table_name='sceneline')
    op.drop_index(op.f('ix_sceneline_character_id'), table_name='sceneline')
    op.drop_table('sceneline')
    op.drop_index(op.f('ix_scene_project_id'), table_name='scene')
    op.drop_table('scene')
    # ### end Alembic commands ###
