"""add_character_language_profiles

Revision ID: bdd37eac4097
Revises: bc60f24b6715
Create Date: 2026-06-04 15:27:02.107792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bdd37eac4097'
down_revision: Union[str, Sequence[str], None] = 'bc60f24b6715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characterlanguageprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_native', sa.Boolean(), nullable=False),
    sa.Column('accent_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characterlanguageprofile_character_id'), 'characterlanguageprofile', ['character_id'], unique=False)
    op.create_index(op.f('ix_characterlanguageprofile_language_code'), 'characterlanguageprofile', ['language_code'], unique=False)
    
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('language_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_code', sa.VARCHAR(), nullable=True))
        
    op.drop_index(op.f('ix_characterlanguageprofile_language_code'), table_name='characterlanguageprofile')
    op.drop_index(op.f('ix_characterlanguageprofile_character_id'), table_name='characterlanguageprofile')
    op.drop_table('characterlanguageprofile')
    # ### end Alembic commands ###
