"""add scene status

Revision ID: d544d5cd3378
Revises: 982e1e553b06
Create Date: 2026-06-09 21:02:14.359545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd544d5cd3378'
down_revision: Union[str, Sequence[str], None] = '982e1e553b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='draft'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene', 'status')
    # ### end Alembic commands ###
