"""pivot to gemini: replace pitch and speed with prompt_style

Revision ID: dff04ad79fd4
Revises: 715a85389e44
Create Date: 2026-06-03 16:36:37.278980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff04ad79fd4'
down_revision: Union[str, Sequence[str], None] = '715a85389e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character') as batch_op:
        batch_op.add_column(sa.Column('prompt_style', sa.String(), nullable=True))
        batch_op.drop_index('ix_character_language_code')
        batch_op.drop_column('pitch')
        batch_op.drop_column('speed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('speed', sa.FLOAT(), nullable=False))
    op.add_column('character', sa.Column('pitch', sa.VARCHAR(), nullable=False))
    op.create_index(op.f('ix_character_language_code'), 'character', ['language_code'], unique=False)
    op.drop_column('character', 'prompt_style')
    # ### end Alembic commands ###
